// scripts/generate-env.js
// Generates public/env.js at build time so the frontend can read API_BASE_URL from Netlify env vars.
// Falls back to localhost during local development.

const fs = require('fs');
const path = require('path');

const apiBaseUrl = process.env.API_BASE_URL || 'http://localhost:3000';
const outputPath = path.resolve(__dirname, '../public/env.js');

const fileContents = `// Auto-generated by scripts/generate-env.js at build time
window.__env = window.__env || {};
window.__env.API_BASE_URL = '${apiBaseUrl.replace(/'/g, "\\'")}';
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, fileContents, 'utf8');

console.log(`Generated env.js with API_BASE_URL=${apiBaseUrl}`);
